repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.11.4
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
           # All-in-one
          - flake8-bugbear
          - flake8-simplify
          - wemake-python-styleguide

          # Clean code
          - flake8-broken-line
          - flake8-class-attributes-order
          - flake8-comprehensions
          - flake8-commas
          - flake8-eradicate
          - flake8-literal
          - flake8-multiline-containers
          - flake8-return
          - flake8-sql

          # Limitations
          - flake8-print
          - flake8-use-fstring

          # Naming
          - flake8-builtins
          - pep8-naming

          # Complexity
          - flake8-cognitive-complexity
          - flake8-functions

          # Docstrings
          - flake8-docstrings

          # Type annotations
          - flake8-annotations
          - flake8-annotations-complexity
          - flake8-new-union-types
          - flake8-pep585

  - repo: https://github.com/PyCQA/pylint
    rev: v2.16.0b0
    hooks:
      - id: pylint
        args: ["--rcfile=setup.cfg"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
